### ISSUE TITLE
Request for the release of datasets?

### ISSUE THREAD

**Issue by Dinxin** [MengtingWan/chainRec#2]
Can you release all the datasets mentioned in your paper, including Steam, Yoochoose, Yelp, GoogleLocal and GoodReads?

**Comment by MengtingWan** [comment]
The datasets are available online:
[Steam/GoogleLocal/GoodReads](https://cseweb.ucsd.edu/~jmcauley/datasets.html)
[Yoochoose](https://recsys.yoochoose.net/)
[Yelp](https://www.yelp.com/dataset/challenge)
